version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/api/Dockerfile
    environment:
      - UPLOAD_PATH=/app/uploads
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 8888:8080
    volumes:
      - shared-volume:/app/uploads
    depends_on:
      - redis
  
  file-processor:
    build:
      context: .
      dockerfile: ./deploy/file-processor/Dockerfile
    command: celery -A main worker --loglevel=info -Q extract
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - shared-volume:/app/uploads
    depends_on:
      - redis
  
  translator:
    build:
      context: .
      dockerfile: ./deploy/translator/Dockerfile
    command: celery -A main worker --loglevel=info -Q translate
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  
  redis:
    image: redis


volumes:
  shared-volume: